# GitHub Pages configuration
plugins:
  - jekyll-gist

# Performance optimizations
sass:
  style: compressed

# Exclude files from processing
exclude:
  - README.md
  - .github/
  - .gitignore

# Include all files
include:
  - .htaccess
  - _headers

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false